In [8]:
import torch
import loss

from volume_dataloader import CTDataSet, CTScanDataModule
from unet import UNet
DATA_PATH = '/media/gaetano/DATA/DATA_NIFTI_JAWS/'

In [9]:
dataset = CTDataSet(DATA_PATH)

In [10]:
model = UNet(in_channels=1,
             out_channels=4,
             n_blocks=4,
             start_filters=32,
             activation='relu',
             normalization='batch',
             conv_mode='same',
             dim=3)

x = dataset[8][0]
x = torch.unsqueeze(x, 0)
print(x.shape)
out = model(x)
print(f'Out: {out.shape}')
print(f'Label: {dataset[0][1].shape}')

torch.Size([1, 1, 75, 75, 75])
Out: torch.Size([1, 4, 75, 75, 75])
Label: torch.Size([1, 4, 75, 75, 75])


In [23]:
tversky = loss.FocalTverskyLoss()
alpha = 0.7
beta = 0.3
gamma = 3/4

tversky(dataset[8][1], dataset[8][1], smooth=1, alpha=alpha, beta=beta, gamma=gamma)

tensor(0.)

In [24]:
x = torch.tensor([[0,0,1], [1,1,1], [1,0,0], [0,1,1]])
y = torch.tensor([[1,1,0], [0,0,0], [0,1,1],[1,0,0]])
print(x.numpy(), y.numpy())
tversky(x, y, smooth=1, alpha=alpha, beta=beta, gamma=gamma)

[[0 0 1]
 [1 1 1]
 [1 0 0]
 [0 1 1]] [[1 1 0]
 [0 0 0]
 [0 1 1]
 [1 0 0]]


tensor(0.8968)